feat: Add the detail page for each country and ability to navigate through border countries
Stage-Research-Center-Jake-Melvin/rest_countries_api pull request #6
Opened 2024-06-16 17:00 UTC by jakemelvin

Here is the link of a video showcasing how the website is working: https://drive.google.com/file/d/1EaM9qxGm-wV4Zw0t6SS9mZQFmr2p6Bq5/view?usp=sharing

2024-06-18 10:47 UTC, libock-serge requested changes

2024-06-18 10:47 UTC, libock-serge commented on src/server/actions.ts
> +export async function searchCountryByCode(code: string): Promise<any> {
Hi @jakemelvin. The use of any is forbidden in Typescript projects. If not, why are we using typescript? Your method doesn't just return any Promise. It returns a Promise of a country. So what you need to do, is to define an interface for a country response, e.g

`export interface GetCountryResponseData {
id : string
name: string
//etc
}`

and your Promise will be a Promise of a Country like this:

Promise<GetCountryResponseData>

2024-06-18 11:02 UTC, yannmarc commented on src/pages/country/[countryCode]/index.tsx
> +      <Link href="/">
@jakemelvin, NextJS has a built-in router hook that you can use. You can create a `const router = useRouter()` and then use a button with an onClick function that calls `router.back()` to navigate backwards.

2024-06-18 17:02 UTC, roy98 approved these changes

2024-06-19 09:07 UTC, libock-serge approved these changes

2024-06-19 09:16 UTC, merged